### ISSUE TITLE
`java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt` after upgrade from 5.0.0-alpha.11 to 5.0.0-alpha.12

### ISSUE THREAD

**Issue by mprins** [square/okhttp#8148]
After upgrading from 5.0.0-alpha.11 to 5.0.0-alpha.12 (for mockwebserver3 and mockwebserver3-junit5) in https://github.com/B3Partners/tailormap-api/pull/669 I'm seeing the below stacktraces:

```

java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt

	at okhttp3.Protocol.<clinit>(Protocol.kt:94)
	at mockwebserver3.MockWebServer.<init>(MockWebServer.kt:181)
	at nl.b3p.tailormap.api.controller.admin.GeoServiceAdminControllerIntegrationTest.loadServiceWithServiceException(GeoServiceAdminControllerIntegrationTest.java:192)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: java.lang.ClassNotFoundException: kotlin.enums.EnumEntriesKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 6 more
```
and 
```
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.Protocol

	at mockwebserver3.MockWebServer.<init>(MockWebServer.kt:181)
	at nl.b3p.tailormap.api.controller.admin.GeoServiceAdminControllerIntegrationTest.loadServiceWithWrongCredentials(GeoServiceAdminControllerIntegrationTest.java:250)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

As far as I understand Kotlin Enum,Entries should be in the kotlin-stdlib jar which is part of the dependency tree (see below). Any hints to resolve this would be welcome.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the MultiThreadedBuilder implementation with a thread count of 17
[INFO] 
[INFO] -------------------< nl.b3p.tailormap:tailormap-api >-------------------
[INFO] Building Tailormap API 11.2.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.3.0:tree (default-cli) @ tailormap-api ---
[INFO] nl.b3p.tailormap:tailormap-api:jar:11.2.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.18:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.18:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.7.18:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.18:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.18:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.13:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.13:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:2.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.18:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.16.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.16.0:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.16.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.18:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.83:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.83:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.31:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.31:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.31:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.7.18:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.7.18:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.31:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.15.Final:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.23:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.9:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.9:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.7.18:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.7.18:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.3.31:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:5.3.31:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.31:compile
[INFO] +- org.springframework.data:spring-data-rest-webmvc:jar:3.7.18:compile
[INFO] |  +- org.springframework.data:spring-data-rest-core:jar:3.7.18:compile
[INFO] |  |  \- org.atteo:evo-inflector:jar:1.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.18:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.7.18:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.7.18:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.12.0:compile
[INFO] |     +- io.micrometer:micrometer-commons:jar:1.12.0:compile
[INFO] |     +- io.micrometer:micrometer-observation:jar:1.12.0:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:runtime
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- io.micrometer:micrometer-registry-prometheus:jar:1.12.0:compile
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.15.0:compile
[INFO] |     \- io.prometheus:simpleclient:jar:0.15.0:compile
[INFO] |        +- io.prometheus:simpleclient_tracer_otel:jar:0.15.0:compile
[INFO] |        |  \- io.prometheus:simpleclient_tracer_common:jar:0.15.0:compile
[INFO] |        \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.15.0:compile
[INFO] +- org.hibernate:hibernate-micrometer:jar:5.6.15.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  \- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] +- org.flywaydb:flyway-core:jar:9.22.3:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-toml:jar:2.16.0:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.9.1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.16.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.16.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.0:compile
[INFO] +- io.hypersistence:hypersistence-utils-hibernate-55:jar:3.7.0:compile
[INFO] +- io.hypersistence:hypersistence-tsid:jar:2.1.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-aop:jar:2.7.18:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.31:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] +- org.springframework.boot:spring-boot-starter-validation:jar:2.7.18:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.83:compile
[INFO] |  \- org.hibernate.validator:hibernate-validator:jar:6.2.5.Final:compile
[INFO] |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.18:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.18:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.18:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.11:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.11:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.3:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.10.1:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.1:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.23:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.31:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.31:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.31:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:2.7.18:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.7.18:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.8.8:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.8.8:compile
[INFO] +- org.springframework.boot:spring-boot-starter-oauth2-client:jar:2.7.18:compile
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.8.8:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:5.8.8:compile
[INFO] |  +- org.springframework.security:spring-security-oauth2-client:jar:5.8.8:compile
[INFO] |  |  +- org.springframework.security:spring-security-oauth2-core:jar:5.8.8:compile
[INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.43.3:compile
[INFO] |  |     +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |     +- com.nimbusds:content-type:jar:2.2:compile
[INFO] |  |     \- com.nimbusds:lang-tag:jar:1.7:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-jose:jar:5.8.8:compile
[INFO] |     \- com.nimbusds:nimbus-jose-jwt:jar:9.24.4:compile
[INFO] +- org.springframework.hateoas:spring-hateoas:jar:1.5.6:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.31:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.31:compile
[INFO] |  \- org.springframework.plugin:spring-plugin-core:jar:2.0.0.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-test:jar:5.8.8:test
[INFO] +- org.junit-pioneer:junit-pioneer:jar:2.2.0:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.1:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.1:test
[INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:compile
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.1:test
[INFO] |  \- org.junit.platform:junit-platform-launcher:jar:1.10.1:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.10.1:test
[INFO] +- com.squareup.okhttp3:mockwebserver3:jar:5.0.0-alpha.12:test
[INFO] |  +- com.squareup.okhttp3:okhttp-jvm:jar:5.0.0-alpha.12:test
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.7.0:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.21:test
[INFO] |     +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.21:test
[INFO] |     \- org.jetbrains:annotations:jar:13.0:test
[INFO] +- com.squareup.okhttp3:mockwebserver3-junit5:jar:5.0.0-alpha.12:test
[INFO] +- org.gaul:modernizer-maven-annotations:jar:2.7.0:compile
[INFO] +- org.postgresql:postgresql:jar:42.7.1:compile
[INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:12.4.1.jre11:compile
[INFO] +- com.oracle.database.jdbc:ojdbc11:jar:23.3.0.23.09:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.14.0:compile
[INFO] +- org.locationtech.jts:jts-core:jar:1.19.0:compile
[INFO] +- org.geotools:gt-main:jar:30.1:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.10.0:compile
[INFO] |  +- com.google.re2j:re2j:jar:1.6:compile
[INFO] |  +- org.ejml:ejml-ddense:jar:0.41:compile
[INFO] |  |  \- org.ejml:ejml-core:jar:0.41:compile
[INFO] |  \- javax.media:jai_core:jar:1.1.3:compile
[INFO] +- org.geotools:gt-geojson-core:jar:30.1:compile
[INFO] |  \- commons-io:commons-io:jar:2.12.0:compile
[INFO] +- org.geotools:gt-wfs-ng:jar:30.1:compile
[INFO] |  +- org.geotools:gt-complex:jar:30.1:compile
[INFO] |  |  \- org.geotools:gt-app-schema-resolver:jar:30.1:compile
[INFO] |  +- org.geotools:gt-gml-geometry-streaming:jar:30.1:compile
[INFO] |  +- org.geotools:gt-http-commons:jar:30.1:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  |     \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.geotools.xsd:gt-xsd-wfs:jar:30.1:compile
[INFO] |  |  +- org.geotools.xsd:gt-xsd-filter:jar:30.1:compile
[INFO] |  |  +- org.geotools.xsd:gt-xsd-fes:jar:30.1:compile
[INFO] |  |  \- org.geotools.xsd:gt-xsd-ows:jar:30.1:compile
[INFO] |  \- org.geotools.ogc:net.opengis.wfs:jar:30.1:compile
[INFO] |     +- org.geotools.ogc:org.w3.xlink:jar:30.1:compile
[INFO] |     \- org.geotools.ogc:net.opengis.fes:jar:30.1:compile
[INFO] +- org.geotools:gt-metadata:jar:30.1:compile
[INFO] |  +- org.geotools:gt-api:jar:30.1:compile
[INFO] |  |  +- systems.uom:systems-common:jar:2.1:compile
[INFO] |  |  |  +- javax.measure:unit-api:jar:2.1.2:compile
[INFO] |  |  |  +- si.uom:si-quantity:jar:2.1:compile
[INFO] |  |  |  \- si.uom:si-units:jar:2.1:compile
[INFO] |  |  \- tech.units:indriya:jar:2.1.3:compile
[INFO] |  |     +- tech.uom.lib:uom-lib-common:jar:2.1:compile
[INFO] |  |     \- javax.inject:javax.inject:jar:1:compile
[INFO] |  \- org.geotools.ogc:net.opengis.ows:jar:30.1:compile
[INFO] +- org.geotools.xsd:gt-xsd-core:jar:30.1:compile
[INFO] |  +- picocontainer:picocontainer:jar:1.2:compile
[INFO] |  +- commons-jxpath:commons-jxpath:jar:1.3:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  +- org.eclipse.emf:org.eclipse.emf.common:jar:2.15.0:compile
[INFO] |  +- org.eclipse.emf:org.eclipse.emf.ecore:jar:2.15.0:compile
[INFO] |  +- org.eclipse.xsd:org.eclipse.xsd:jar:2.12.0:compile
[INFO] |  \- org.eclipse.emf:org.eclipse.emf.ecore.xmi:jar:2.15.0:compile
[INFO] +- org.geotools.xsd:gt-xsd-gml3:jar:30.1:compile
[INFO] |  \- org.geotools.xsd:gt-xsd-gml2:jar:30.1:compile
[INFO] +- org.geotools:gt-http:jar:30.1:compile
[INFO] +- org.geotools:gt-cql:jar:30.1:compile
[INFO] +- org.geotools:gt-xml:jar:30.1:compile
[INFO] |  \- org.apache.xml:xml-commons-resolver:jar:1.2:compile
[INFO] +- org.geotools:gt-wms:jar:30.1:compile
[INFO] |  +- org.geotools:gt-coverage:jar:30.1:compile
[INFO] |  |  +- javax.media:jai_imageio:jar:1.1:compile
[INFO] |  |  +- it.geosolutions.imageio-ext:imageio-ext-tiff:jar:1.4.7:compile
[INFO] |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-utilities:jar:1.4.7:compile
[INFO] |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-geocore:jar:1.4.7:compile
[INFO] |  |  |  |  +- it.geosolutions.imageio-ext:imageio-ext-streams:jar:1.4.7:compile
[INFO] |  |  |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  |  +- io.airlift:aircompressor:jar:0.20:compile
[INFO] |  |  |  \- javax.media:jai_codec:jar:1.1.3:compile
[INFO] |  |  +- org.jaitools:jt-zonalstats:jar:1.6.0:compile
[INFO] |  |  +- org.jaitools:jt-utils:jar:1.6.0:compile
[INFO] |  |  +- it.geosolutions.jaiext.affine:jt-affine:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.algebra:jt-algebra:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.bandmerge:jt-bandmerge:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.bandselect:jt-bandselect:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.bandcombine:jt-bandcombine:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.border:jt-border:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.buffer:jt-buffer:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.crop:jt-crop:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.iterators:jt-iterators:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.lookup:jt-lookup:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.mosaic:jt-mosaic:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.nullop:jt-nullop:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.rescale:jt-rescale:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.scale:jt-scale:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.scale2:jt-scale2:jar:1.1.24:compile
[INFO] |  |  |  \- org.huldra.math:bigint:jar:0.7.1:compile
[INFO] |  |  +- it.geosolutions.jaiext.stats:jt-stats:jar:1.1.24:compile
[INFO] |  |  |  \- com.google.guava:guava:jar:27.0-jre:compile
[INFO] |  |  |     +- com.google.guava:failureaccess:jar:1.0:compile
[INFO] |  |  |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |     +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |  |  |     +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  |  |     +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  |  +- it.geosolutions.jaiext.translate:jt-translate:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.utilities:jt-utilities:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.warp:jt-warp:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.zonal:jt-zonal:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.binarize:jt-binarize:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.format:jt-format:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.colorconvert:jt-colorconvert:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.errordiffusion:jt-errordiffusion:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.orderdither:jt-orderdither:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.colorindexer:jt-colorindexer:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.imagefunction:jt-imagefunction:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.piecewise:jt-piecewise:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.classifier:jt-classifier:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.rlookup:jt-rlookup:jar:1.1.24:compile
[INFO] |  |  +- it.geosolutions.jaiext.vectorbin:jt-vectorbin:jar:1.1.24:compile
[INFO] |  |  \- it.geosolutions.jaiext.shadedrelief:jt-shadedrelief:jar:1.1.24:compile
[INFO] |  \- org.geotools:gt-render:jar:30.1:compile
[INFO] |     \- com.conversantmedia:disruptor:jar:1.2.15:compile
[INFO] +- org.geotools:gt-wmts:jar:30.1:compile
[INFO] |  +- org.geotools:gt-tile-client:jar:30.1:compile
[INFO] |  \- org.geotools.xsd:gt-xsd-wmts:jar:30.1:compile
[INFO] |     \- org.geotools.ogc:net.opengis.wmts:jar:30.1:compile
[INFO] +- org.geotools:gt-referencing:jar:30.1:compile
[INFO] |  +- commons-pool:commons-pool:jar:1.6:compile
[INFO] |  +- it.geosolutions.jgridshift:jgridshift-core:jar:1.3:compile
[INFO] |  \- net.sf.geographiclib:GeographicLib-Java:jar:1.49:compile
[INFO] +- org.geotools:gt-epsg-hsql:jar:30.1:compile
[INFO] |  \- org.hsqldb:hsqldb:jar:2.7.2:compile
[INFO] +- org.geotools:gt-jdbc:jar:30.1:compile
[INFO] |  \- commons-dbcp:commons-dbcp:jar:1.4:compile
[INFO] +- org.geotools.jdbc:gt-jdbc-oracle:jar:30.1:compile
[INFO] +- org.geotools.jdbc:gt-jdbc-postgis:jar:30.1:compile
[INFO] +- org.geotools.jdbc:gt-jdbc-sqlserver:jar:30.1:compile
[INFO] +- io.swagger.core.v3:swagger-annotations:jar:2.2.19:compile
[INFO] +- org.webjars:swagger-ui:jar:5.10.3:compile
[INFO] +- org.webjars:webjars-locator-core:jar:0.55:compile
[INFO] |  \- io.github.classgraph:classgraph:jar:4.8.149:compile
[INFO] +- io.sentry:sentry-spring-boot-starter:jar:7.1.0:compile
[INFO] |  \- io.sentry:sentry-spring-boot:jar:7.1.0:compile
[INFO] |     \- io.sentry:sentry-spring:jar:7.1.0:compile
[INFO] +- io.sentry:sentry-jdbc:jar:7.1.0:compile
[INFO] |  \- p6spy:p6spy:jar:3.9.1:compile
[INFO] +- io.sentry:sentry:jar:7.1.0:compile
[INFO] +- me.gosimple:nbvcxz:jar:1.5.1:compile
[INFO] \- ch.rasc:sse-eventbus:jar:1.1.9:compile
[INFO]    \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.585 s (Wall Clock)
[INFO] Finished at: 2023-12-19T11:53:36+01:00
[INFO] ------------------------------------------------------------------------

```

**Comment by JakeWharton** [comment]
Somehow you're getting version 1.6.21 of the Kotlin stdlib instead of 1.9.21 which is what 5.0 alpha 12 depends on. Do you have an explicit dependency on the stdlib somewhere? Or are you letting it come in transitively?

**Comment by mprins** [comment]
Yes I just noticed (wake up Mark!); it's the version that is specified in the spring-boot-dependencies BOM; I've added an override, so now I'm at 1.9.21 and that fixes the problem. Thanks for looking into this.

```
...
[INFO] +- com.squareup.okhttp3:mockwebserver3:jar:5.0.0-alpha.12:test
[INFO] |  +- com.squareup.okhttp3:okhttp-jvm:jar:5.0.0-alpha.12:test
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.7.0:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.21:test
[INFO] |     \- org.jetbrains:annotations:jar:13.0:test
[INFO] +- com.squareup.okhttp3:mockwebserver3-junit5:jar:5.0.0-alpha.12:test
...
```

**Comment by sebastianharder** [comment]
@JakeWharton, are there any requirements documented for 5.x regarding Java version and Kotlin version?
Asking because I still have to use Java 11 and Kotlin 1.7 in a project and get the error `META-INF/okhttp.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.`
