### ISSUE TITLE
NoSuchMethodError in 2.0.0-RC2

### ISSUE THREAD

**Issue by josomers** [square/okhttp#925]
Hi there,

After I upgraded from 2.0.0-RC1 to RC2, I got the following exception. My stack trace doesn't contain more information and I've no clue where to look first.

Can you take a look?

Thanks!

```
java.lang.NoSuchMethodError: com.squareup.okhttp.OkHttpClient.setConnectTimeout
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.setConnectTimeout(HttpURLConnectionImpl.java:242)
            at com.android.volley.toolbox.HurlStack.openConnection(HurlStack.java:165)
            at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:102)
            at com.android.volley.CustomBasicNetwork.performRequest(CustomBasicNetwork.java:88)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)
```
