### ISSUE TITLE
NoSuchMethodError: Duration.Companion.fromRawValue-UwyO8pc with Kotlin 2.3

### ISSUE THREAD

**Issue by xfluo-cn** [square/okhttp#9347]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

| Component          | Kotlin Version | Result                                    |
| ------------------ | -------------- | ----------------------------------------- |
| IntelliJ 2025.3.1  | 2.3.10/2.3.20  | Bundled stdlib                            |
| OkHttp 5.3.2.      | 2.2.21          | Compiled against old `Duration` internals |
| **Outcome**        | **Crash**      | `NoSuchMethodError: fromRawValue-UwyO8pc` |

my dependency tree showing Kotlin 2.3.10 forcing over 2.2.x
...
+--- org.jetbrains.kotlin:kotlin-stdlib:2.3.10
|         +--- org.jetbrains.kotlin:kotlin-stdlib:2.2.0 -> 2.3.10 (*)
|                   \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.0 -> 2.3.10 (*)
|         |         \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.20 -> 2.3.10 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.21 -> 2.3.10 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.21 -> 2.3.10 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib:2.2.21 -> 2.3.10 (*)
...

{code:java}
2026-03-02 16:07:12,159 [  66530] SEVERE - #c.i.i.p.PluginManager - 'long kotlin.time.Duration$Companion.fromRawValue-UwyO8pc$kotlin_stdlib(long)'
java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.fromRawValue-UwyO8pc$kotlin_stdlib(long)'
	at kotlin.time.DurationKt.durationOfNanos(Duration.kt:1593)
	at kotlin.time.DurationKt.toDuration(Duration.kt:969)
	at okhttp3.internal._CacheControlCommonKt.commonForceCache(-CacheControlCommon.kt:65)
	at okhttp3.CacheControl.<clinit>(CacheControl.kt:276)
	at okhttp3.Request.cacheControl(Request.kt:126)
	at okhttp3.internal.cache.CacheStrategy$Factory.compute(CacheStrategy.kt:131)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:126)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:126)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:126)
	at com.xxx.company.network.interceptors.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:51)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:126)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:226)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:178)
{code}

**Comment by xfluo-cn** [comment]
Same environment can work with Kotlin 2.2.21

**Comment by yschimke** [comment]
Similar issue here https://github.com/InsertKoinIO/koin-compiler-plugin/issues/3

It's not directly in the OkHttp code, so I'm not sure we can fix. 

Call chain is

https://github.com/square/okhttp/blob/okhttp_5.3.x/okhttp/src/commonJvmAndroid/kotlin/okhttp3/internal/-CacheControlCommon.kt#L65

https://github.com/JetBrains/kotlin/blob/4f0831525e26d26e56a3102c868cefc7b12e2161/libraries/stdlib/src/kotlin/time/Duration.kt#L168

https://github.com/JetBrains/kotlin/blob/4f0831525e26d26e56a3102c868cefc7b12e2161/libraries/stdlib/src/kotlin/time/Duration.kt#L971

The last one is not inlined.

**Comment by faraz152** [comment]
Hi! I'd like to work on this.

The crash happens because `Int.MAX_VALUE.seconds` in `-CacheControlCommon.kt:65` goes through `kotlin.time.Duration` extension functions that call internal stdlib methods (`Duration.Companion.fromRawValue`). When a user's project upgrades to Kotlin 2.3 stdlib, those internal method signatures change, causing the `NoSuchMethodError`.

My fix: replace `Int.MAX_VALUE.seconds` (which uses `kotlin.time.Duration`) with `maxStale(Int.MAX_VALUE, TimeUnit.SECONDS)` (which uses OkHttp's own `TimeUnit`-based overload). This avoids the `kotlin.time.Duration` code path entirely, so OkHttp compiled with Kotlin 2.2.x works correctly at runtime with Kotlin 2.3.x stdlib.

PR incoming.

**Comment by fzhinkin** [comment]
[It seems like](https://youtrack.jetbrains.com/issue/KT-85558) the problem is caused by parts of the stdlib being loaded by different class loaders from different stdlib versions.

If so, neither it relates to the Kotlin stdlib, nor to OkHttp. But it would be interesting to see why that happened and if something could be improved on the KGP side or on the IjIdea plugins (it's about an Idea's plugin, right?) side to prevent the issue.

About the version table from the summary:
 <!DOCTYPE html>
IntelliJ 2025.3.1 | 2.3.10/2.3.20
-- | --

`2025.3` should be bundled w/ `2.2.20`, shouldn't it? https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#bundled-stdlib-versions

**Comment by BoD** [comment]
> 2025.3 should be bundled w/ 2.2.20, shouldn't it?

Exactly, I'm also puzzled. We are facing the same crash in our IntelliJ plugin when [upgrading](https://github.com/apollographql/apollo-intellij-plugin/pull/130) to platform 252 and Kotlin 2.2.20, and so far I haven’t been able to understand the root cause. For now as a workaround I've avoided using the incriminating duration functions, but of course that feels fragile and worrying.
