### ISSUE TITLE
Could not initialize class okhttp3.CacheControl

### ISSUE THREAD

**Issue by AvengerLjj** [square/okhttp#7585]
when i upgrade okhttp3 to 5.0

2022-12-29 14:17:30.845 [TID:d192ab9a603446478ebe4a9f0851ec67.80.16722946508388521] [http-nio-8300-exec-8] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] -Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause
java.io.IOException: canceled due to java.lang.NoClassDefFoundError: Could not initialize class okhttp3.CacheControl
	at okhttp3.internal.connection.RealCall$AsyncCall.run$original$tJil77xy(RealCall.kt:546)
	at okhttp3.internal.connection.RealCall$AsyncCall.run$original$tJil77xy$accessor$NFXbJ2mh(RealCall.kt)
	at okhttp3.internal.connection.RealCall$AsyncCall$auxiliary$UasiRKGn.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class okhttp3.CacheControl
		at okhttp3.Request.cacheControl(Request.kt:115)
		at okhttp3.internal.cache.CacheStrategy$Factory.compute(CacheStrategy.kt:134)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:52)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp$original$PTIiI5bO(RealCall.kt:205)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp$original$PTIiI5bO$accessor$1uv8VM8q(RealCall.kt)
		at okhttp3.internal.connection.RealCall$auxiliary$ZYCCNmLB.call(Unknown Source)
		at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt)
		at okhttp3.internal.connection.RealCall$AsyncCall.run$original$tJil77xy(RealCall.kt:533)
		... 7 common frames omitted
