### ISSUE TITLE
Error in OKhttp 2.1.0 "No static method hasRequestBody"

### ISSUE THREAD

**Issue by amitchintawar** [square/okhttp#1151]
Hi,

I upgraded the OKHttp to 2.1.0 and suddenly I started having below error. The same request works on 2.1.0 RC1 release jar.

retrofit.RetrofitError: No static method hasRequestBody(Ljava/lang/String;)Z in class Lcom/squareup/okhttp/internal/http/HttpMethod; or its super classes (declaration of 'com.squareup.okhttp.internal.http.HttpMethod' appears in /data/app/myapp-1/base.apk)

I have latest jars of okio(1.0.1), okhttp-urlconnection(2.0.0) and retrofit(1.6.1).

Other Details:
1. IDE : Eclipse
2. Device: Nexus 5(Android 4.4.4) and Nexus 5(Android L Preview)
3. Logcat:

11-13 11:04:49.623: D/Retrofit(2738): java.lang.NoSuchMethodError: No static method hasRequestBody(Ljava/lang/String;)Z in class Lcom/squareup/okhttp/internal/http/HttpMethod; or its super classes (declaration of 'com.squareup.okhttp.internal.http.HttpMethod' appears in /data/app/myapp-1/base.apk)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:321)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:303)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:364)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
11-13 11:04:49.623: D/Retrofit(2738):   at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
11-13 11:04:49.623: D/Retrofit(2738):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-13 11:04:49.623: D/Retrofit(2738):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-13 11:04:49.623: D/Retrofit(2738):   at retrofit.Platform$Android$2$1.run(Platform.java:142)
11-13 11:04:49.623: D/Retrofit(2738):   at java.lang.Thread.run(Thread.java:818)
11-13 11:04:49.623: D/Retrofit(2738): ---- END ERROR
