### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3.internal.Util on Android 4.4 Version?

### ISSUE THREAD

**Issue by AruLNadhaN** [square/okhttp#2349]
I have added the library through  Gradle. It works fine on Version 5.0 & above.
I saw [this issue](https://github.com/square/okhttp/issues/282). I haven't got a solution

```
    compile 'com.squareup.okhttp3:okhttp:3.1.2'
    compile 'com.squareup.okio:okio:1.6.0'
```

```
 Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.Util
 at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:61)
```

**Comment by honeyv** [comment]
Hi AruLNadhaN,

I am facing same problem. Please let me know, how you solve this issue.


Thanks

**Comment by swankjesse** [comment]
Just run `mvn compile` to cause generated sources to be generated.

**Comment by AruLNadhaN** [comment]
The problem was not related to the okhttp library. The Logcat lies sometimes :).
I have `multiDexEnabled true` in my build. gradle file. But My Application class was not extending `MultiDexApplication`. Extending My Class with `MultiDexApplication` Fixed the Issue

**Comment by centerzx** [comment]
@AruLNadhaN , Good！Thanks !

**Comment by Parorisim** [comment]
@AruLNadhaN , big thanks!

**Comment by quangcm** [comment]
> The problem was not related to the okhttp library. The Logcat lies sometimes :)

> I have multiDexEnabled true in my build.gradle file. But My Application class was not extending MultiDexApplication. Extending my class with MultiDexApplication fixed the Issue

You saved my day. Thanks so much.
How do you know that?

**Comment by nadia-am** [comment]
Thanks so much.

**Comment by rahulvis** [comment]
HTTP FAILED: javax.net.ssl.SSLException: Connection closed by peer

pre lollipop Error

**Comment by erluxman** [comment]
@AruLNadhaN  thank you so much bro :) you saved me after 2 days of badluck..

**Comment by huangshuyuan** [comment]
The problem was not related to the okhttp library. The Logcat lies sometimes :)

I have multiDexEnabled true in my build.gradle file. But My Application class was not extending MultiDexApplication. Extending my class with MultiDexApplication fixed the Issue

this can be ok@AruLNadhaN

**Comment by kinpowoo** [comment]
thanks so much
