### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by juliocotta** [square/okhttp#1582]
I am having the same issue as #1543. Is there any workaround, test or something I can do (to solve or to help debug the problem)? It is happening with Android 4.4.* and 5.*, many different manufactors.
 it is not an public API, so I can't provide the server URL, but I can try execute any tests you want.
```java
javax.net.ssl.SSLHandshakeException: Handshake failed
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:242)
       at com.squareup.okhttp.Connection.connect(Connection.java:159)
       at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.access$100(Call.java:34)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb7928f58: Failure in SSL library, usually a protocol error
error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:765 0xadeb0edd:0x00000000)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:242)
       at com.squareup.okhttp.Connection.connect(Connection.java:159)
       at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.access$100(Call.java:34)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by nfuller** [comment]
My comment on #1543 regarding why this occurs and how to debug should still be valid, as is the offer to help if you can provide a URL.

**Comment by Idhor** [comment]
See https://github.com/square/okhttp/issues/1543#issuecomment-95970332

**Comment by swankjesse** [comment]
It's likely due to our stricter crypto requirements. You should work around is to use `ConnectionSpec` to include these obsolete cipher suites for your negotiation.

**Comment by swankjesse** [comment]
Try this;
```
client.setConnectionSpecs(Collections.singletonList(spec));ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)  
    .tlsVersions(TlsVersion.TLS_1_2)
    .cipherSuites(
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
        CipherSuite.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
        CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA)
    .build();
client.setConnectionSpecs(Collections.singletonList(spec));
```

**Comment by Idhor** [comment]
Copy pasted the connection spec and now both okhttp 2.2.0 and okhttp 2.3.0 fails with the same error

**Comment by nfuller** [comment]
What Jesse said....

Idhor@ Regarding your URL, from https://www.ssllabs.com/ssltest/index.html it looks like there may be no intersection between the set of ciphers it supports and the set that OkHttp restricts to.

It apparently supports: 
TLS_RSA_WITH_RC4_128_MD5
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_EXPORT_WITH_RC4_40_MD5
TLS_RSA_WITH_DES_CBC_SHA
TLS_RSA_EXPORT_WITH_DES40_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

None of these are on the default list in ConnectionSpec.

**Comment by juliocotta** [comment]
@nfuller , I went to the ssllabs e ran it agaist my servers URL, I got two IPs and in each one I had the results here https://gist.github.com/juliocotta/0b8ee6712ed2c8efe4b5
but I am not eble to analise it, could you help me?

**Comment by Idhor** [comment]
Those urls are generated from user actions and i have to support all of them so i need to find a configuration less stricter
Anyway even if i enable a supported cipher on 2.3.0 it fails in the same way, is changed something else after 2.2.0 beyond the default ConnectionSpec configuration?

**Comment by nfuller** [comment]
@Idhor Which cipher did you enable? Which version of Android are you using?

There must be at least one cipher in "{ciphers enabled by default on android} /\ {ciphers enabled by OkHttp} /\ {ciphers supported by server}" for negotiation to succeed.

If you want to avoid the OkHttp restriction entirely, you can build a connection spec without setting cipher suites and it will just use what Android enables by default. According to the docs Android enables TLS_RSA_WITH_RC4_128_MD5 by default up to API 19 (KitKat) but it will be disabled afterwards. It's still supported, though, just not enabled.

The reason Android doesn't enable a lot of supported ciphers by default is that they are insecure / broken in some way. Same for OkHttp.

If you don't mind that and want to go ahead, then you can install your own SSLSocketFactory (e.g. OkHttpClient.setSslSocketFactory()) and delegate every method to the platform's SSLSocketFactory (SSLSocketFactory.getDefault()) and explicitly enable the ciphers you want (assuming they are supported) before returning the socket. To avoid the OkHttp restrictions, you will also need to use a ConnectionSpec that includes those cipher or leaves the ciphers completely unset.

**Comment by nfuller** [comment]
@juliocotta

*TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 - OkHttp: yes, Android: 20+*
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - OkHttp: no, Android: no
*TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - OkHttp: yes, Android: 20+*
**TLS_DHE_RSA_WITH_AES_128_CBC_SHA - OkHttp: yes, Android: 9+**
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 - OkHttp: no, Android: 20+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - OkHttp: no, Android: no
*TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - OkHttp: yes, Android: 20+*
*TLS_RSA_WITH_AES_128_GCM_SHA256 - OkHttp: yes, Android: 20+*
TLS_RSA_WITH_AES_128_CBC_SHA256 - OkHttp: no, Android: no
**TLS_RSA_WITH_AES_128_CBC_SHA - OkHttp: yes, Android: 9+**
TLS_RSA_WITH_AES_256_GCM_SHA384 - OkHttp: no, Android: 20+
TLS_RSA_WITH_AES_256_CBC_SHA256 - OkHttp: no, Android: no
TLS_RSA_WITH_AES_256_CBC_SHA - OkHttp: yes, Android: 20+

I'd expect the ones in bold to work on most devices.
I'd expect the ones in italics to work on Android API 20+ (effectively lollipop)

If you want to remove OkHttp from the equation, you can try something like this from your app:

        SSLSocket socket = (SSLSocket) SSLSocketFactory.getDefault().createSocket("www.google.com", 443);
        socket.startHandshake();
        SSLSession session = socket.getSession();
        System.out.println(session.getProtocol());
        System.out.println(session.getCipherSuite());

Replace www.google.com with your IP / hostname. That should tell you what Android would choose by default, if it can negotiate.

@Idhor I just tried this with your host. By default on a recent AOSP build, Android appears to pick SSL_RSA_WITH_RC4_128_SHA (called CipherSuite.TLS_RSA_WITH_RC4_128_SHA in OkHttp).

**Comment by juliocotta** [comment]
I tested (using just the SSLSocket) with some phones using one of the IP addresses ssllabs returned:
Android 2.3.6 (Samsung GT-S5830C)
TLSv1
TLS_DHE_RSA_WITH_AES_128_CBC_SHA

Android 4.4.4 (Moto G)
TLSv1
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

Android 5.1 (Nexus 5):
TLSv1.2
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

The thing is, in those phones I don't have the handshake problem, I know it happens because I crashlytics show me.


I don't know if it is relevante, but I also tested the code using a Linux machine (kubuntu 14.10 64 bits), but this is the result:
``` java
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at Main.main(Main.java:65)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
	... 8 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 14 more
```

**Comment by nfuller** [comment]
@juliocotta - I'm wondering if the problems on those devices are related to manufacturer-introduced differences, or certificate-chain issues. I would have expected a certificate validation failure to manifest differently, but I'm not sure. If you can share the information about the devices and the versions of Android they report I _might_ be able to get hold of one to check. I'm not sure if the desktop java stack trace you provided is helpful: I have a feeling that the default may reject everything by default, but I don't know for sure.

**Comment by juliocotta** [comment]
@nfuller , I have some other handshake logs that Crashlytics provide (sadly crashlytics groups all handshake errors in just one entry and I had to browse through it to separate them), maybe there is something related. I know some of the errors in the gist below are network related, but the first one seemed very related to the problem.


https://gist.github.com/juliocotta/04207c8030b7b803d2e0

**Comment by juliocotta** [comment]
I just updated the gist with some more error logs, something with "SSLPeerUnverifiedException" came up in some other crashlytics entry..

**Comment by iNoles** [comment]
@juliocotta I noticed two WiFi Hotspots for SSLPeerUnverifiedException

**Comment by nfuller** [comment]
As @iNoles said, some are probably a MITM like WiFi hotspots ("boingohotspot") or DNS providers causing some of the certificate validation issues. This is probably correct that it's failing. I'm guessing that some of the CertPathValidationExceptions ("Trust anchor for certification path not found.") may be caused by that same thing (but where the cert presented is signed by a root CA that isn't trusted, rather than just being for an incorrect subject).

Timeouts, connection closed by peer: not much to say. Network issues unless repeatable.

I think the ones at the bottom in Spdy3$Writer and SpdyStream _might_ be something like #1552.

These ones are more interesting for this report. I'll see if I can get hold of one of these.

SM-G313ML DEVICE - Android 4.4.2
LG-D855 DEVICE  - Android 5.0
XT1069 DEVICE - Android 5.0.2
XT1033 DEVICE - Android 5.0.2
GT-I9192 DEVICE - Android 4.4.2
ASUS_T00J DEVICE -Android 4.4.2

**Comment by juliocotta** [comment]
Guys, translate it to my language, please.
The stacktraces helped anything?
So the hotspot thing is not in the app or library, right? Is there anything I can do about the MITM (man in the middle attack, right?)? The handling of the MITM is OK, right?
Is there anything also I could do to help here? Maybe release a update of the app with some extra tracking or testing.

**Comment by nfuller** [comment]
@juliocotta 

The stack traces show the problems you see can be divided into distinct groups. They definitely helped with that. I'm interpreting this bug to be about TLS negotiation issues you are experiencing, so I'm ignoring ones not related to that (timeouts, server closing the socket, etc.). Unfortunately, with TLS negotiation failures, the stack trace only shows the final failure, which isn't very informative.

MITM means that somebody has inserted themselves into the connection in some way. It might be an attack, but often hotspots and ISPs do it too. Several of the stack traces are clearly for wi-fi hotspot vendors. They control the network and are probably trying to get the user to sign up / pay before they can use it.

Sometimes people run with a non-default DNS provider (e.g. OpenDNS) that blocks domains and redirects people.

Either way, you go to a site called https://xyz.com/ and you end up on a site that to you appears to be on https://xyz.com/ but is giving you a certificate for https://notxyz.com/. OkHttp will correctly fail the connection. In a browser like Chrome you'd see a warning along the lines of "This isn't the page you think it is". This is working as intended. You'll need to deal with it in your app: it's a legitimate failure.

Other exceptions showed that a certificate was provided by the server, but it wasn't trusted because the root certificate wasn't on the client device (or may have expired). I'm also ignoring these. It's also working as intended.

For better debugging, I have a change I'd like to make to OkHttp, but I haven't had time to get to it and probably won't for another week or two. I work on the Android platform so my contributions to OkHttp are sporadic and typically driven by the needs of Android. This falls into "nice to have" and is behind some other bugs in OkHttp I _must_ fix.

Here's a rough outline if you wanted to have a go for your own needs or contribute:

https://github.com/square/okhttp/blob/master/okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java#L457

Where it says getLastConnectException(), we have the other failures available, currently hidden away inside RouteException. On platforms that support Exception.addSuppressedException() (e.g. Java 1.7, Android after ICS) we could take those exceptions and add them to the exception we throw as suppressed exceptions. Then they'd show up to the caller and we'd have more info to go on. The fiddly bits are that I'd like it to work for Call as well, and I need to put in the appropriate reflection checks for addSuppressedException() to do it on the platforms that support it and not do it (or do something different) on platforms that don't. I need to find a home for the shared logic, and I'd need to write tests and test it manually.

**Comment by juliocotta** [comment]
Thanks for the explanation @nfuller !
Ok, so I tried to add this:

```java
public final class RouteException extends Exception {
  public List<IOException> getConnectExceptions() {
    return connectExceptions;
  }
...
}
```
```java
List<IOException> ioExceptions = e.getConnectExceptions();
      // don't add the last IOException to the suppressed list.
      for(int index = 0; index < ioExceptions.size() -1; ++index) {
    	  IOException ioException = ioExceptions.get(index);
         try {
            toThrow.addSuppressed(ioException);
         } catch (NoSuchMethodError e1) {
            // ignore it. works on java 1.7 and ICS+ enough to debug what I need.
         }
      }
```
but in the "mvn package" I got this:
```
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.11:check (default) @ okhttp-urlconnection ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[ERROR] /home/julio/git/okhttp/okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java:463: Undefined reference: void java.io.IOException.addSuppressed(Throwable)

```
Any tip?

**Comment by iNoles** [comment]
@juliocotta Are you compiled on Java 7?

**Comment by juliocotta** [comment]
```
$ javac -version
javac 1.8.0_40
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

```

**Comment by juliocotta** [comment]
I have it compiling now, that I set the pom.xml of okhttp-urlconnection project with
```
<plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>animal-sniffer-maven-plugin</artifactId>
            <version>1.7</version>
            <executions>
               <execution>
                  <id>signature-check</id>
                  <phase>verify</phase>
                  <goals>
                     <goal>check</goal>
                  </goals>
               </execution>
            </executions>
            <configuration>
               <signature>
                  <groupId>org.codehaus.mojo.signature</groupId>
                  <artifactId>java17</artifactId>
                  <version>1.0</version>
               </signature>
            </configuration>
          </plugin>
        <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
    		<configuration>
        		<source>1.7</source>
        		<target>1.7</target>
        		<showDeprecation>true</showDeprecation>
        		<showWarnings>true</showWarnings>
        		<fork>true</fork>
    		</configuration>
    	</plugin>
```
then I removed the gradle entry for OkHttp of my project and copied the okhttp-2.4.0-SNAPSHOT.jar and okhttp-android-support-2.4.0-SNAPSHOT.jar files, the project compiled (after I added okio to gradle), but I had to change some POST methods to add a "@Body Object object" parameter to make my POST calls work again ( OKHttp seems to complain about POSTs needing to have bodies...is it a change to okhttp 2.4 or bug?)

And I also changed this to make add in the reverse order.
```java
      List<IOException> ioExceptions = e.getConnectExceptions();
      // don't add the last IOException to the suppressed.
      for(int index = ioExceptions.size() -1; index >= 0 -1; --index) {
    	  IOException ioException = ioExceptions.get(index);
         try {
            toThrow.addSuppressed(ioException);
         } catch (NoSuchMethodError e1) {
            // ignore it. works on java 1.7 and ICS+ enough for debug.
         }
      }
```
now, how to create a test to this?

**Comment by iNoles** [comment]
Looks like you removed 1.6 runtime checks. 

```java
try {
Method suppressedMethods = toThrow.class.getMethod("addSuppressed", Throwable.class);
if (suppressedMethods != null) {
suppressedMethods.invoke(toThrow, ioException);
}
} catch (NoSuchMethodError e1) { 
} catch (SecurityException e2) {
}

**Comment by iNoles** [comment]
There is a way to get back to old 1.6 runtime checks is Java Reflection.

```java
Method method =  toThrow.class.getDeclaredMethod("addSuppressed", Throwable.class);
method.invoke(toThrow, ioException);

**Comment by juliocotta** [comment]
@iNoles , you are right, I could go back to java 6 with the code your provided.Thanks!
However, I think I am not able to test it. Any idea?
```java
// Give up; recovery is not possible.
      IOException toThrow = e.getLastConnectException();
      List<IOException> ioExceptions = e.getConnectExceptions();
      // don't add the last IOException to the suppressed.
      for(int index = ioExceptions.size() -2; index >= 0; --index) {
    	  IOException ioException = ioExceptions.get(index);
         try {
        	 Method method =  IOException.class.getDeclaredMethod("addSuppressed", Throwable.class);
        	 method.invoke(toThrow, ioException);
         } catch (NoSuchMethodException e1) {
        	 break;
             // ignore it. works on java 1.7 and ICS+ enough for debug.
		} catch (SecurityException e1) {
       	 break;
         // ignore it. works on java 1.7 and ICS+ enough for debug.
		} catch (IllegalAccessException e1) {
       	 break;
         // ignore it. works on java 1.7 and ICS+ enough for debug.
		} catch (IllegalArgumentException e1) {
       	 break;
         // ignore it. works on java 1.7 and ICS+ enough for debug.
		} catch (InvocationTargetException e1) {
       	 break;
         // ignore it. works on java 1.7 and ICS+ enough for debug.
		}
      }
```

**Comment by nfuller** [comment]
I created a pull request here for exception change: https://github.com/square/okhttp/pull/1596

@juliocotta If you don't mind sharing a URL/server address privately let me know. I've managed to get hold of a XT1068 (not exactly the same as one you mentioned, but close), and I may be able to get hold of a Asus Zenphone (something like a ASUS_T00J). I need a server to test with though.

**Comment by juliocotta** [comment]
@nfuller , how can we talk privately?

**Comment by nfuller** [comment]
My google.com email address would be simplest. It's just nfuller@

**Comment by swankjesse** [comment]
Closing because there is no further action required here as far as I can tell.
